apiVersion: kdex.dev/v1alpha1
kind: KDexClusterFaaSAdaptor
metadata:
  labels:
    kdex.dev/default: "true"
    {{- include "kdex-knative-faas-adaptor.labels" . | nindent 4 }}
  name: {{ include "kdex-knative-faas-adaptor.fullname" . }}
spec:
  deployer:
    env:
    - name: DEBUG_SECURITY
      value: "true"
    image: {{ printf "%s:%s" .Values.image.repository (.Values.image.tag | default .Chart.AppVersion) | quote }}
    command: ["/deployer", "deploy"]
    serviceAccountName: {{ include "kdex-knative-faas-adaptor.serviceAccountName" . }}
  observer:
    image: {{ printf "%s:%s" .Values.image.repository (.Values.image.tag | default .Chart.AppVersion) | quote }}
    command: ["/deployer", "observe"]
    schedule: "*/5 * * * *"
    serviceAccountName: {{ include "kdex-knative-faas-adaptor.serviceAccountName" . }}
  defaultBuilderGenerator: tiny/go
  builders:
  - builderRef:
      kind: ClusterBuilder
      name: tiny-builder
    languages:
    - go
    - rust
    name: tiny
  - builderRef:
      kind: ClusterBuilder
      name: base-builder
    languages:
    - nodejs
    - python
    name: base
  generators:
  - entrypoint: "./cmd/main.go"
    git:
      image: {{ printf "%s:%s" .Values.generatorGit.image.repository .Values.generatorGit.image.tag | quote }}
      committerEmail: {{ .Values.generatorGit.committerEmail | quote }}
      committerName: {{ .Values.generatorGit.committerName | quote }}
    image: ghcr.io/kdex-tech/fngogen:0.1.3
    language: go
  - entrypoint: "./src/main.ts"
    git:
      image: {{ printf "%s:%s" .Values.generatorGit.image.repository .Values.generatorGit.image.tag | quote }}
      committerEmail: {{ .Values.generatorGit.committerEmail | quote }}
      committerName: {{ .Values.generatorGit.committerName | quote }}
    image: ghcr.io/kdex-tech/fnnodejsgen:0.1.2
    language: nodejs
  provider: knative
