apiVersion: v1
kind: ConfigMap
metadata:
  name: config-network
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/component: networking
    app.kubernetes.io/version: "1.20.1"
data:
  ingress.class: "traefik.ingress.networking.knative.dev"
